"""Overlay drawing and labeling helpers."""

from weapon_ai.overlay.draw import (
    COLOR_GUN_GHOST_BGR,
    COLOR_GUN_OBJECT_BGR,
    COLOR_GUN_WEAPON_BGR,
    COLOR_PERSON_ARMED_BGR,
    COLOR_PERSON_ARMED_PROVISIONAL_BGR,
    COLOR_PERSON_ARMED_CONCEALED_BGR,
    COLOR_PERSON_AMBIGUOUS_BGR,
    COLOR_PERSON_OBJECT_BGR,
    FIREARM_GHOST_CONF,
    OVERLAY_FONT,
    OVERLAY_SCALE_GUN,
    OVERLAY_SCALE_PERSON,
    OVERLAY_SCALE_STATUS,
    OVERLAY_THICK,
    OVERLAY_THICK_STATUS,
    draw_label_above_box,
    overlay_draw_style,
)
from weapon_ai.overlay.labels import (
    armed_weapon_bracket,
    gun_box_class_name,
    gun_box_person_ridx,
    person_key_for_row,
    person_overlay_label,
    person_public_name,
    person_weapon_bracket,
)

__all__ = [
    "COLOR_GUN_GHOST_BGR",
    "COLOR_GUN_OBJECT_BGR",
    "COLOR_GUN_WEAPON_BGR",
    "COLOR_PERSON_ARMED_BGR",
    "COLOR_PERSON_ARMED_PROVISIONAL_BGR",
    "COLOR_PERSON_ARMED_CONCEALED_BGR",
    "COLOR_PERSON_AMBIGUOUS_BGR",
    "COLOR_PERSON_OBJECT_BGR",
    "FIREARM_GHOST_CONF",
    "OVERLAY_FONT",
    "OVERLAY_SCALE_GUN",
    "OVERLAY_SCALE_PERSON",
    "OVERLAY_SCALE_STATUS",
    "OVERLAY_THICK",
    "OVERLAY_THICK_STATUS",
    "armed_weapon_bracket",
    "draw_label_above_box",
    "gun_box_class_name",
    "gun_box_person_ridx",
    "overlay_draw_style",
    "person_key_for_row",
    "person_overlay_label",
    "person_public_name",
    "person_weapon_bracket",
]
